### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined index.js:238

### ISSUE THREAD

**Issue by kevzettler** [YR/simple-traits#1]
Hi I was trying out this library and following one of the simple examples from the read me and its throwing an error. 

Heres my script.

```
var Trait = require('trait');

var t = Trait({
  foo: Trait.required,
  bar: function bar () {
    return this.foo;
  },
  baz: 'baz'
});
```

And heres the error

```
/Users/kevzettler/VoxLords/node_modules/trait/index.js:238
        attr._origin = attr.value;
                           ^
TypeError: Cannot read property 'value' of undefined
    at Object.Attributes.add (/Users/kevzettler/VoxLords/node_modules/trait/index.js:238:28)
    at Object.Attributes (/Users/kevzettler/VoxLords/node_modules/trait/index.js:27:14)
    at trait (/Users/kevzettler/VoxLords/node_modules/trait/index.js:10:12)
    at Object.<anonymous> (/Users/kevzettler/VoxLords/traittest.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by kevzettler** [comment]
should be 
`var Trait = require('simple-traits');`
